server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restapi-db?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
  jackson:
    '[data-format]': 'yyyy-MM-dd HH:mm:ss'

logging:
  level:
    '[org.springframework.web]': debug
    '[com.restapi]': info
    '[org.hibernate.SQL]': debug
    '[org.hibernate.type.descriptor.sql.BasicBinder]': trace
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd } [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: app.log
    path: classpath



